module.exports = {
  changePassword: require('./changePassword'),
  electionDates: require('./electionDates'),
  resetPassword: require('./resetPassword'),
  userEntryForm: require('./userEntryForm'),
  patchPromote: require('./patchPromote'),
  patchResolve: require('./patchResolve'),
  celebration: require('./celebration'),
  contactInfo: require('./contactInfo'),
  unsubscribe: require('./unsubscribe'),
  userUpdate: require('./userUpdate'),
  settings: require('./settings'),
  address: require('./address'),
  receipt: require('./receipt'),
  intent: require('./intent'),
  paymentMethod: require('./paymentMethod'),
  pol: require('./pol'),
  contributing: require('./contributing'),
};
