const { Reset, Change, Forgot } = require('./password'),
  { New, Update, Receipt, Test, ContributingInquiry } = require('./info'),
  { Image } = require('./error'),
  {
    Locked,
    Quitter,
    Promoted,
    JoinedUp,
    JoiningUp,
  } = require('./account'),
  {
    DefunctCelebrationNotification,
    DefunctCelebrationWarning,
    ElectionDateNotification,
    ElectionDateChanged,
    ChallengerDisappeared,
    ChallengerReappeared,
    ChallengerAppeared,
    IncumbentDroppedOut,
    PacLimitReached,
  } = require('./alerts');

module.exports = {
  emails: {
    DefunctCelebrationNotification,
    DefunctCelebrationWarning,
    ElectionDateNotification,
    ElectionDateChanged,
    ChallengerDisappeared,
    ChallengerReappeared,
    ChallengerAppeared,
    IncumbentDroppedOut,
    PacLimitReached,
    JoiningUp,
    JoinedUp,
    Promoted,
    Receipt,
    Quitter,
    Change,
    Forgot,
    Locked,
    Update,
    Image,
    Reset,
    New,
    Test,
    ContributingInquiry,
  },
};
